image: docker:latest

before_script:
- docker login -u dineshpillai -p Pill2017
- export KUBECONFIG=/etc/kubernetes/admin.conf

stages:
 - deletenamespace
 - build
 - test
 - createnamespace
 - deployhz
 - deploystreamer

deleteNameSpace:
  stage: deletenamespace
  script:
   - kubectl delete namespace mu-architecture-demo
  allow_failure: true

build:
 stage: build 
 script:
    - mvn -version
    - mvn clean package install -DskipTests
    - cd streamprocessor
    - mvn clean package install -DskipTests docker:build	
    - docker push dineshpillai/innovation-mu-streamers
 dependencies:
    - deleteNameSpace
   
createNameSpace:
  stage: createnamespace
  script: 
   - kubectl create namespace mu-architecture-demo
  allow_failure: true
  dependencies:
    - build

deployhz:
  stage: deployhz
  script:
    - cd kubernetes	
    - kubectl apply -f run-mzk.yaml
    - kubectl apply -f run-hz-jet-cluster.yaml
  dependencies:
    - build 

deployStreamer:
  stage: deploystreamer
  script: 
   - cd kubernetes
   - kubectl apply -f trade-streamer-deployments.yaml
   - kubectl apply -f price-streamer-deployments.yaml
  dependencies:
    - deployhz
