image: docker:latest

before_script:
- docker login -u dineshpillai -p Pill2017

build:
  script:
    - mvn -version
    - mvn clean package install -DskipTests
    - cd streamprocessor
    - mvn docker:build	
    - docker push dineshpillai/innovation-mu-streamers
