image: docker:latest

before_script:
- docker login -u dineshpillai -p Pill2017
- export KUBECONFIG=/etc/kubernetes/admin.conf

stages:
 - deletenamespace
 - build
 - test
 - createnamespace
 - deployhz
 - deployflink 

deleteNameSpace:
  stage: deletenamespace
  script:
   - kubectl delete namespace mu-architecture-demo
  allow_failure: true

build:
 stage: build 
 script:
    - mvn -version
    - mvn clean package install -DskipTests
    - cd streamprocessor
    - mvn clean package install -DskipTests docker:build	
    - docker push dineshpillai/innovation-mu-streamers
    - cd ../trade-imdg
    - mvn docker:build
    - docker push dineshpillai/innovation-trade-imdg
    - cd ../trade-injector
    - mvn docker:build
    - docker push dineshpillai/innovation-trade-injector
    - cd ../tradequerymicroservice
    - mvn docker:build
    - docker push dineshpillai/imcs-tradequeryservice 
    - cd ../positionqueryservice
    - mvn docker:build
    - docker push dineshpillai/imcs-positionqueryservice 
 dependencies:
    - deleteNameSpace
   
createNameSpace:
  stage: createnamespace
  script: 
   - kubectl create namespace mu-architecture-demo
  allow_failure: true
  dependencies:
    - build

deployhz:
  stage: deployhz
  script:
    - cd kubernetes	
    - kubectl apply -f run-mzk.yaml
    - kubectl apply -f run-hz-jet-cluster.yaml
    - sleep 20s
    - kubectl apply -f run-apps-reports.yaml
    - sleep 20s
    - kubectl apply -f run-querymicroservices.yaml 
  dependencies:
    - build 

deployStreamer:
  stage: deploystreamer
  script: 
   - cd kubernetes
   - kubectl apply -f trade-streamer-deployments.yaml
   - kubectl apply -f price-streamer-deployment.yaml
   - kubectl apply -f position-streamer-deployment.yaml
  dependencies:
    - deployhz

deployFlinkCluster:
  stage: deployflink
  script:
   - cd kubernetes
   - kubectl apply -f jobmanager-controller.yaml
   - kubectl apply -f jobmanager-service.yaml  
   - kubectl apply -f taskmanager-controller.yaml
