image: docker:latest

before_script:
- docker login -u dineshpillai -p Pill2017
- export KUBECONFIG=/etc/kubernetes/admin.conf

stages:
 - build
 - test
 - deploy

build:
  script:
    - mvn -version
    - mvn clean package install -DskipTests
    - cd streamprocessor
    - mvn docker:build	
    - docker push dineshpillai/innovation-mu-streamers

deploy:
  script:
    - cd ../kubernetes	
    - kubectl apply -f run-mzk.yaml
