---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: price-streamer
  namespace: mu-architecture-demo
  labels:
    name: price-streamer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: price-streamer
    spec:
      hostAliases:
      - ip: "138.68.176.187"
        hostnames:
        - "1524d2683b90"
      containers:
      - image: dineshpillai/innovation-mu-streamers:1.0-SNAPSHOT
        name: price-streamer
        imagePullPolicy: Always
        args: ["hzJetClusterProfile=tradeStreamer=0,priceStreamer=1,positionStreamer=0", "kafka_url=kafka:9092", "hzHost=trade-imdg.vnet", "runs=1000", "delay=6000"]
        ports:
        - name: price-streamer
          containerPort: 6701
        resources: {}
      

