---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trade-imdg
  namespace: mu-architecture-demo
  labels:
    name: trade-imdg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: trade-imdg
    spec:
      hostAliases:
      - ip: "178.62.124.180"
        hostnames:
        - "a8bceadb696d"
      containers:
      - image: dineshpillai/innovation-trade-imdg:0.0.1-SNAPSHOT
        name: trade-imdg
        imagePullPolicy: Always
        ports:
        - name: trade-imdg
          containerPort: 5701
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: trade-imdg-service
  namespace: mu-architecture-demo
  labels:
    app: trade-imdg
spec:
  ports:
    - port: 5701
  selector:
    app: trade-imdg

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trade-streamer
  namespace: mu-architecture-demo
  labels:
    name: trade-streamer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: trade-streamer
    spec:
      hostAliases:
      - ip: "178.62.124.180"
        hostnames:
        - "a8bceadb696d"
      containers:
      - image: dineshpillai/innovation-mu-streamers:1.0-SNAPSHOT
        name: trade-streamer
        imagePullPolicy: Always
        args: ["hzJetClusterProfile=tradeStreamer=1,priceStreamer=0,positionStreamer=0", "kafka_url=kafka:9092", "hzHost=trade-imdg.vnet", "runs=1000", "delay=6000"]
        ports:
        - name: trade-streamer
          containerPort: 6701
        resources: {}


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: price-streamer
  namespace: mu-architecture-demo
  labels:
    name: price-streamer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: price-streamer
    spec:
      hostAliases:
      - ip: "178.62.124.180"
        hostnames:
        - "a8bceadb696d"
      containers:
      - image: dineshpillai/innovation-mu-streamers:1.0-SNAPSHOT
        name: price-streamer
        imagePullPolicy: Always
        args: ["hzJetClusterProfile=tradeStreamer=0,priceStreamer=1,positionStreamer=0", "kafka_url=kafka:9092", "hzHost=trade-imdg.vnet", "runs=1000", "delay=6000"]
        ports:
        - name: price-streamer
          containerPort: 6701
        resources: {}
