---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trade-imdg
  namespace: mu-architecture-demo
  labels:
    name: trade-imdg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: trade-imdg
    spec:
      hostAliases:
      - ip: "178.62.124.180"
        hostnames:
        - "0a6db884f721"
      containers:
      - image: dineshpillai/innovation-trade-imdg:0.0.1-SNAPSHOT
        name: trade-imdg
        imagePullPolicy: Always
        ports:
        - name: trade-imdg
          containerPort: 5701
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: trade-imdg-service
  namespace: mu-architecture-demo
  labels:
    app: trade-imdg
spec:
  ports:
    - port: 5701
  selector:
    app: trade-imdg

